# Docker Swarm Stack Configuration
# Deploy with: docker stack deploy -c swarm-stack.yml llm_agent

version: '3.8'

# Overlay network for service discovery and inter-service communication
networks:
  llm_network:
    driver: overlay
    driver_opts:
      com.docker.network.driver.overlay.vxlan_list: "4789"

services:
  # Router: receives requests and forwards to healthy workers
  router:
    image: llm-router:latest
    ports:
      # Port 8000 externally, 5000 internally (Gunicorn port)
      - target: 5000
        published: 8000
        protocol: tcp
        mode: host
    networks:
      - llm_network
    environment:
      # Use service name for internal Swarm DNS load balancing
      WORKER_SERVICE: "llm_worker"
      WORKER_PORT: "5000"
      HOST: "0.0.0.0"
      PORT: "5000"
      LOG_LEVEL: "INFO"
      HEALTH_TIMEOUT: "2"
      REQUEST_TIMEOUT: "30"
      MAX_RETRIES: "2"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
      placement:
        # Run router on manager node for stability
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s

  # Workers: run LLM models and generate text
  llm_worker:
    image: llm-worker:latest
    networks:
      - llm_network
    environment:
      # Listen on all interfaces within container
      HOST: "0.0.0.0"
      PORT: "5000"
      MODEL_NAME: "distilgpt2"
      LOG_LEVEL: "INFO"
      DO_SAMPLE: "True"
      MAX_LENGTH: "100"
      TEMPERATURE: "0.7"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # Spread workers across different nodes
      placement:
        max_replicas_per_node: 1
      # Resource limits to prevent node overload
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
      update_config:
        parallelism: 1
        delay: 10s
