version: '3.8'

networks:
  llm_overlay:
    driver: overlay

services:
  router:
    image: distributed_llm_agent_router:latest
    ports:
      - target: 5000
        published: 8000
        protocol: tcp
        mode: host
    networks:
      - llm_overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  llm_worker:
    image: distributed_llm_agent_worker:latest
    networks:
      - llm_overlay
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
