version: '3.8'

networks:
  llm_network:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16

services:
  router:
    image: llm-router:latest
    ports:
      - target: 5000
        published: 8000
        protocol: tcp
        mode: host
    networks:
      - llm_network
    environment:
      WORKER_SERVICE: "llm_worker"
      WORKER_PORT: "5000"
      HOST: "0.0.0.0"
      PORT: "5000"
      LOG_LEVEL: "INFO"
      HEALTH_TIMEOUT: "2"
      REQUEST_TIMEOUT: "30"
      MAX_RETRIES: "2"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager

  llm_worker:
    image: llm-worker:latest
    networks:
      - llm_network
    environment:
      HOST: "0.0.0.0"
      PORT: "5000"
      DPR_QUESTION_ENCODER: "facebook/dpr-question_encoder-single-nq-base"
      DPR_CONTEXT_ENCODER: "facebook/dpr-ctx_encoder-single-nq-base"
      ENCODE_BATCH: "32"
      LOG_LEVEL: "INFO"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
